blank_issues_enabled: false
contact_links:
  - name: FAQs
    url: https://github.com/infinitepower18/WSA-Sideloader#faq
    about: Have you taken a look at the FAQs?
  - name: General support
    url: https://github.com/infinitepower18/WSA-Sideloader/discussions
    about: For support queries, please post in the project's discussion.
  - name: Email support
    url: https://forms.gle/Fkbyh7WRX17mQ7dW9
    about: Select this option for email support.
